##
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional
#       These are not needed for plotting only


channel: mumu

baselineCuts: "q_1*q_2<0 && iso_1<0.15 && iso_2<0.15 && !lepton_vetoes && metfilter"

regions:
    ZMM: 
        definition: "m_ll>50 && m_ll<150 && abs(eta_1) < 2.1 && abs(eta_2) < 2.4 "
        title: "50 < m_mumu < 150 GeV"
        fname: "zttregion"
